name: boxet
description: Gifts App.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+10

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  carousel_pro: ^1.0.0
  vector_math: ^2.0.8
  font_awesome_flutter: 8.4.0
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  lazy_load_scrollview: 1.0.1
  material_design_icons_flutter: ^3.4.4795
  shared_preferences: ^2.0.5 
  firebase_core: ^1.0.4  # add dependency for Firebase Core
  firebase_auth_web: ^1.0.7
  firebase_analytics: ^8.0.1
  firebase_auth: ^1.1.1
  firebase_storage: ^8.0.4
  firebase_crashlytics: ^2.0.1
  flutter_spinkit: "^4.1.1"
  cloud_firestore: ^1.0.6
  curved_navigation_bar: ^0.3.1
  smooth_star_rating: 1.1.1
  sign_in_with_apple: ^3.0.0
  google_maps_flutter: ^2.0.3
  location: ^4.1.1
  flutter_custom_clippers: ^1.1.1
  shimmer: ^1.1.1
  clippy_flutter: ^1.1.1
  fab_circular_menu: ^1.0.0
  flutter_staggered_animations: "^0.1.3"
  cached_network_image: ^2.1.0
  menu_button: ^1.2.1
  google_sign_in: ^4.5.3
  flutter_facebook_login: ^3.0.0
  image_picker: ^0.7.4
  connectivity: ^3.0.3
  firebase_messaging: ^9.1.2
  flutter_local_notifications: ^5.0.0+1
  flare_flutter: ^2.0.6
  video_player: ^1.0.1
  
dependency_overrides:
  intl: ^0.17.0-nullsafety.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.8.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/boxet.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/map_style.json
    - assets/images/heart.png
    - assets/images/mom.png
    - assets/images/male.png
    - assets/images/female.png
    - assets/images/kids.png
    - assets/images/giftDel.jpg
    - assets/images/googleicon.png
    - assets/images/facebook.png
    - assets/images/profile.png
    - assets/images/profilef.png
    - assets/images/inboxassist.jpg
    - assets/loading.flr
    - assets/zzz.flr
    - assets/images/candies.png
    - assets/images/boxet.png
    - assets/lang/en.json
    - assets/lang/ar.json
    - assets/images/zzz.png
    - assets/images/zzzw.png
    - assets/images/qqq.png
    - assets/images/handmade.png
    


    



  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:

  - family: Lobster
    fonts:
      - asset: fonts/Lobster-Regular.ttf
      
  - family: MyFlutterApp
    fonts:
      - asset: fonts/MyFlutterApp.ttf
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
